import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { useResource, useStore } from "@/lib/store";
import { Button } from "@/components/ui/button";
import { ErrorBox, Field } from "@/components/shared";

const secretFields = ["apiKey", "secretKey", "clientId", "clientSecret", "username", "password"];
const fieldLabels: Record<string, string> = { apiKey: "API Key", secretKey: "Secret Key", clientId: "Client ID", clientSecret: "Client Secret", username: "Merchant email", password: "Merchant password" };
export function Couriers() {
  const { data, error, reload } = useResource<any>("/admin/couriers", 0);
  const { notice } = useStore();
  const [provider, setProvider] = useState<"steadfast" | "pathao">("steadfast");
  const [form, setForm] = useState<any>({ enabled: false, active: false, environment: "sandbox", storeId: 0, defaultWeight: 0.5, verifiedContract: false });
  const [showSecrets, setShowSecrets] = useState<Record<string, boolean>>({});
  const [stores, setStores] = useState<any[]>([]);
  const [dirty, setDirty] = useState(false);
  const current = data?.[provider] ?? { enabled: false, active: false, environment: "sandbox", storeId: 0, defaultWeight: 0.5, verifiedContract: false, configured: {} };
  useEffect(() => { if (data?.[provider]) { const next = data[provider]; setForm({ enabled: !!next.enabled, active: !!next.active, environment: next.environment || "sandbox", storeId: next.storeId || 0, defaultWeight: next.defaultWeight || 0.5, verifiedContract: !!next.verifiedContract }); setDirty(false); } }, [provider, data]);
  if (!data) return error ? <ErrorBox error={error} /> : <div className="p-8 text-sm text-muted-foreground">Loading courier settings…</div>;
  const load = () => { setForm({ enabled: current.enabled, active: current.active, environment: current.environment, storeId: current.storeId, defaultWeight: current.defaultWeight, verifiedContract: current.verifiedContract }); setDirty(false); };
  const change = (next: any) => { setForm(next); setDirty(true); };
  return <div className="mx-auto max-w-6xl space-y-6 pb-10">
    <div className="rounded-[2rem] border bg-card p-6 shadow-sm sm:p-8">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b pb-5"><h1 className="flex items-center gap-3 text-xl font-bold"><span className="text-primary">🚚</span> Automated Courier Integration (Pathao & Steadfast)</h1><span className="rounded-full bg-emerald-100 px-4 py-2 text-xs font-bold text-emerald-700">{current.active ? `${provider === "pathao" ? "Pathao" : "Steadfast"} Active ✓` : "Manual / Offline Active"}</span></div>
      <p className="mt-6 text-sm font-bold">Select Courier Provider</p>
      <div className="mt-3 grid gap-3 md:grid-cols-3"><button className={`rounded-2xl border-2 p-6 font-bold transition ${!current.active && !data.pathao?.active && !data.steadfast?.active ? "border-primary bg-primary text-white" : "bg-card"}`} onClick={() => change({ ...form, enabled: false, active: false })}>✋<br />Manual / Offline</button><button className={`rounded-2xl border-2 p-6 font-bold transition ${provider === "pathao" ? "border-primary bg-primary text-white" : "bg-card"}`} onClick={() => setProvider("pathao")}>🏍<br />Pathao Courier</button><button className={`rounded-2xl border-2 p-6 font-bold transition ${provider === "steadfast" ? "border-primary bg-primary text-white" : "bg-card"}`} onClick={() => setProvider("steadfast")}>🚚<br />Steadfast Courier</button></div>
      <div className="mt-5 border-t pt-6">
      <div className="rounded-2xl border border-sky-200 bg-sky-50/70 p-5 text-sm"><div className="flex flex-wrap items-center justify-between gap-3"><strong>{provider === "pathao" ? "🏍 Pathao Courier Developer API Setup" : "🚚 Steadfast Courier API Integration"}</strong><a className="font-bold text-sky-700 underline" href={provider === "pathao" ? "https://merchant.pathao.com/courier/developer-api" : "https://packzy.com/"} target="_blank" rel="noreferrer">Open {provider === "pathao" ? "Pathao Developer Portal" : "Steadfast Portal"} ↗</a></div><p className="mt-2 text-muted-foreground">{provider === "pathao" ? "Set up your Pathao credentials, then test the OAuth connection and fetch registered pickup stores." : "Get your Api-Key and Secret-Key from the API Settings tab in your Steadfast merchant panel."}</p>{provider === "pathao" && <div className="mt-3 rounded-xl border bg-white/80 p-3 text-muted-foreground"><b>How to get your credentials:</b><ol className="ml-5 list-decimal"><li>Open the Pathao Developer API portal.</li><li>Copy Client ID and Client Secret.</li><li>Enter your merchant email and password.</li><li>Test the connection and choose a pickup store.</li></ol></div>}</div>
      {!data.encryptionReady && <p className="text-sm text-destructive">Set COURIER_ENCRYPTION_KEY to a 64-character hex value on the server before saving credentials.</p>}
      <div className="grid gap-5 sm:grid-cols-2">
        {provider === "pathao" ? <Field label="Environment"><select className="field" value={form.environment} onChange={e => { setStores([]); change({ ...form, environment: e.target.value }); }}><option value="production">Production (Live Deliveries)</option><option value="sandbox">Sandbox / Test</option></select></Field>
          : <p className="self-end rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 sm:col-span-2">Steadfast has no sandbox. Every booking creates a real parcel, so test with a real order you intend to ship.</p>}
        {provider === "pathao" && <Field label="Pickup Store ID / Warehouse ID">{stores.length ? <select className="field" value={form.storeId || ""} onChange={e => change({ ...form, storeId: Number(e.target.value) })}><option value="">Select pickup store</option>{stores.map(x => <option key={x.store_id} value={x.store_id}>{x.store_name} (#{x.store_id}){x.store_address ? ` · ${x.store_address}` : ""}</option>)}</select> : <input className="field" type="number" min="0" value={form.storeId} onChange={e => change({ ...form, storeId: Number(e.target.value) })} />}</Field>}
        {provider === "pathao" && <Field label="Default parcel weight (kg)"><input className="field" type="number" min="0.5" max="10" step="0.1" value={form.defaultWeight} onChange={e => change({ ...form, defaultWeight: Number(e.target.value) })} /></Field>}
        {secretFields.filter(f => provider === "steadfast" ? ["apiKey", "secretKey"].includes(f) : ["clientId", "clientSecret", "username", "password"].includes(f)).map(key => { const sensitive = key.toLowerCase().includes("key") || key.toLowerCase().includes("secret") || key === "password", masked = current.masked?.[key] || ""; return <Field key={key} label={fieldLabels[key]}><div className="relative"><input className="field pr-16" type={sensitive && !showSecrets[key] ? "password" : "text"} placeholder={current.configured?.[key] ? "" : "Required"} value={form[key] || masked} onFocus={e => { if (!form[key] && masked) e.currentTarget.select(); }} onChange={e => change({ ...form, [key]: e.target.value === masked ? "" : e.target.value })} />{sensitive && <button type="button" className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-muted-foreground" onClick={() => setShowSecrets(s => ({ ...s, [key]: !s[key] }))}>{showSecrets[key] ? "Hide" : "Show"}</button>}</div></Field>; })}
      </div>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={e => change({ ...form, enabled: e.target.checked, active: e.target.checked })} /> Enable and use {provider} as the active courier</label>
      <div className="flex flex-wrap gap-3"><Button variant="outline" onClick={async () => { try { const result = await api(`/admin/couriers/${provider}/test`, "POST", form); setStores(result.stores || []); notice(provider === "pathao" ? `Pathao connected. ${result.stores?.length ? "Choose your pickup store above." : "No pickup stores found in this account."}` : "Steadfast connected successfully"); } catch (e) { notice((e as Error).message); } }}>⚡ Test {provider === "pathao" ? "Connection & Fetch Stores" : "Credentials"}</Button></div>
      </div>
    </div>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-card p-5"><span className={`rounded-full px-3 py-2 text-xs font-bold ${dirty ? "bg-amber-100 text-amber-700" : "bg-emerald-100 text-emerald-700"}`}>{dirty ? "● You have unsaved changes" : "● All settings up to date"}</span><div className="flex gap-3"><Button variant="outline" disabled={!dirty} onClick={load}>Discard Changes</Button><Button disabled={!dirty} onClick={async () => { try { const payload = { ...form }; for (const key of secretFields) if (typeof payload[key] === "string" && payload[key].startsWith("••")) payload[key] = ""; const result = await api<any>(`/admin/couriers/${provider}`, "PUT", payload); await reload(); notice(result.success ? "✓ Settings saved successfully" : "✓ Courier settings saved"); } catch (e) { notice((e as Error).message); } }}>▣ Save Settings</Button></div></div>
  </div>;
}
