import { useState } from "react";
import { api } from "@/lib/api";
import { useResource, useStore } from "@/lib/store";
import { Button } from "@/components/ui/button";
import { ErrorBox, Field } from "@/components/shared";

const events = ["PageView", "ViewContent", "Search", "AddToCart", "InitiateCheckout", "AddPaymentInfo", "Purchase"];
export function Tracking() {
  const { data, error, reload } = useResource<any>("/admin/tracking"), { notice } = useStore();
  const [form, setForm] = useState<any>(null), [show, setShow] = useState(false), [testing, setTesting] = useState(false), [result, setResult] = useState<any>(null), [dirty, setDirty] = useState(false);
  if (!data) return error ? <ErrorBox error={error} /> : <div className="panel p-8">Loading tracking settings…</div>;
  const value = form || data.settings, update = (next: any) => { setForm(next); setDirty(true); };
  const save = async () => { try { await api("/admin/tracking", "PUT", value); setForm(null); setDirty(false); await reload(); notice("Tracking settings saved"); } catch (e) { notice((e as Error).message); } };
  return <div className="mx-auto max-w-6xl space-y-6 pb-10">
    <section className="rounded-[2rem] border bg-card p-6 shadow-sm sm:p-8">
      <div className="flex flex-wrap items-start justify-between gap-4 border-b pb-5"><div><h1 className="text-xl font-bold">◉ Meta Pixel & Conversions API (CAPI)</h1><p className="mt-1 text-sm text-muted-foreground">Track PageView, ViewContent, AddToCart, InitiateCheckout & Purchase events on Facebook and Instagram Ads.</p></div><span className="rounded-full bg-emerald-100 px-3 py-2 text-xs font-bold text-emerald-700">Server CAPI + Browser Pixel ✓</span></div>
      <div className="mt-6 rounded-2xl border border-sky-200 bg-sky-50 p-5 text-sm"><strong>🛡 High-Precision Deduplication & Conversion Tracking:</strong><p className="mt-2">Browser Pixel and server-side Conversions API send events with a shared event_id. Meta automatically removes duplicate events for accurate attribution.</p></div>
      <div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="1. Meta Pixel ID"><input className="field" value={value.pixelId} onChange={e => update({ ...value, pixelId: e.target.value })} placeholder="Pixel ID" /></Field><Field label="2. Test Event Code (Optional for Testing)"><input className="field" value={value.testCode} onChange={e => update({ ...value, testCode: e.target.value })} placeholder="Test event code" /></Field></div>
      {value.testCode && <div className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">⚠ Test Event Code is active. Real customer purchases will be marked as test events and will not be attributed to live ads.</div>}
      <div className="mt-5"><Field label="3. Conversions API (CAPI) Access Token"><div className="flex gap-2"><input className="field" type={show ? "text" : "password"} value={value.accessToken || ""} placeholder={data.settings.configured ? "Saved securely; leave blank to keep" : "Access token"} onChange={e => update({ ...value, accessToken: e.target.value })} /><Button type="button" variant="outline" onClick={() => setShow(!show)}>{show ? "Hide Token" : "Show Token"}</Button></div></Field></div>
      <div className="mt-5 rounded-2xl border bg-secondary p-5"><h3 className="font-bold">⚡ Live Meta CAPI Diagnostic Tool</h3><p className="text-sm text-muted-foreground">Send an immediate test event to Facebook Graph API to check token validity and live connection.</p><div className="mt-4 flex flex-wrap gap-3"><select className="field w-auto" id="tracking-event">{events.map(x => <option key={x}>{x}</option>)}</select><Button disabled={testing} onClick={async () => { setTesting(true); setResult(null); try { const e = document.getElementById("tracking-event") as HTMLSelectElement; setResult(await api("/admin/tracking/test", "POST", { eventName: e.value })); } catch (e) { setResult({ error: (e as Error).message }); } finally { setTesting(false); } }}>{testing ? "Testing…" : "🚀 Test Conversions API"}</Button></div>{result && <div className={`mt-4 rounded-xl p-4 text-sm ${result.error ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{result.error ? `✕ Meta CAPI Connection Failed: ${result.error}` : `✓ Meta CAPI Connected Successfully · Pixel ${result.pixelId} · Event ID ${result.eventId} · ${result.apiStatus}`}</div>}</div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2">{events.map(e => <label key={e} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span>✓ {e}</span><span className="text-emerald-600">Active</span></label>)}</div>
    </section>
    <section className="rounded-[2rem] border bg-card p-6 shadow-sm sm:p-8"><h2 className="text-xl font-bold">◔ Other Multi-Channel Tracking (TikTok & Google)</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="TikTok Pixel ID"><input className="field" value={value.tiktokPixelId} onChange={e => update({ ...value, tiktokPixelId: e.target.value })} /></Field><Field label="Google Tag / GA4 Measurement ID"><input className="field" value={value.googleMeasurementId} onChange={e => update({ ...value, googleMeasurementId: e.target.value })} /></Field></div><p className="mt-3 text-sm text-muted-foreground">Google Analytics 4 Measurement ID or Google Tag Manager Container ID.</p></section>
    <section className="rounded-[2rem] border bg-card p-6 shadow-sm sm:p-8"><h2 className="text-xl font-bold">Advanced Tracking Controls</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["advancedMatching","Enable Meta Advanced Matching"],["serverSide","Enable Server Side Tracking"],["cookieConsent","Enable Cookie Consent Tracking"],["dynamicProducts","Enable Dynamic Product Tracking"],["offlineUpload","Enable Offline Conversion Upload"]].map(([key,label]) => <label key={key} className="flex items-center gap-3 rounded-xl border p-4 text-sm"><input type="checkbox" checked={!!value[key]} onChange={e => update({ ...value, [key]: e.target.checked })} />{label}</label>)}</div></section>
    <section className="rounded-2xl border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-4"><span className={`rounded-full px-3 py-2 text-xs font-bold ${dirty ? "bg-amber-100 text-amber-700" : "bg-emerald-100 text-emerald-700"}`}>{dirty ? "● You have unsaved changes" : "● All settings up to date ✓"}</span><div className="flex gap-3"><Button variant="outline" disabled={!dirty} onClick={() => { setForm(null); setDirty(false); }}>Clear</Button><Button disabled={!dirty} onClick={save}>▣ Save Settings</Button></div></div></section>
  </div>;
}
